# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9adab4f46a68a4ce8bb72e0edafccefb"
name = "GoHighLevel Integration"
handle = "gohighlevel-integration-1"
application_url = "https://authenticluxury.io"
embedded = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "products/create" ]
  uri = "/webhooks/products-create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://authenticluxury.io/auth/callback",
  "https://authenticluxury.io/auth/shopify/callback",
  "https://authenticluxury.io/api/auth/callback"
]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true
