# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "caec388204048b32c199650ad00869b8"
name = "real-authenticator-v1"
handle = "real-authenticator-v1"
application_url = "https://0cd8-103-125-177-158.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "products/create" ]
  uri = "/webhooks/products-create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://0cd8-103-125-177-158.ngrok-free.app/auth/callback",
  "https://0cd8-103-125-177-158.ngrok-free.app/auth/shopify/callback",
  "https://0cd8-103-125-177-158.ngrok-free.app/api/auth/callback"
]

[pos]
embedded = false
